# Generated by Django 3.0.6 on 2020-06-17 08:10

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0045_assign_unlock_grouppagepermission'),
        ('home', '0003_auto_20200601_1537'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeShownPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('featured_title', models.CharField(blank=True, help_text='Title to display above the promo copy', max_length=255, null=True)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='shown_pages', to='home.HomePage')),
                ('shown_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shown_page', to='wagtailcore.Page')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
