# Generated by Django 3.1 on 2020-09-01 07:27

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0022_uploadedimage'),
        ('newapp', '0002_apppage_likes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='defaultbannerimage',
            options={'verbose_name_plural': 'Default image for banner/logo'},
        ),
        migrations.AddField(
            model_name='apppage',
            name='latlng',
            field=models.CharField(blank=True, default=None, help_text="Comma separated lat/long. (Ex. 64.144367, -21.939182)                               Right click Google Maps and select 'What's Here'", max_length=36, null=True, validators=[django.core.validators.RegexValidator(code='invalid_lat_long', message='Lat Long must be a comma-separated numeric lat and long', regex='^(\\-?\\d+(\\.\\d+)?),\\s*(\\-?\\d+(\\.\\d+)?)$')]),
        ),
        migrations.AlterField(
            model_name='defaultbannerimage',
            name='image',
            field=models.ForeignKey(blank=True, help_text='Default image for banner/logo', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
    ]
