# Generated by Django 3.1 on 2020-09-01 07:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0003_auto_20200901_1027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apppage',
            name='latlng',
            field=models.CharField(blank=True, default=None, help_text="Comma separated lat/long. (Ex. 64.144367, -21.939182)                               Right click Google Maps and select 'What's Here'", max_length=128, null=True, validators=[django.core.validators.RegexValidator(code='invalid_lat_long', message='Lat Long must be a comma-separated numeric lat and long', regex='^(\\-?\\d+(\\.\\d+)?),\\s*(\\-?\\d+(\\.\\d+)?)$')]),
        ),
    ]
