# Generated by Django 3.0.6 on 2020-06-12 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0022_uploadedimage'),
        ('newapp', '0009_auto_20200612_1150'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefaultBannerImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ForeignKey(blank=True, help_text='Default image for banner', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
            ],
            options={
                'verbose_name_plural': 'Default image for banner',
            },
        ),
    ]
