# Generated by Django 3.0.6 on 2020-06-15 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0022_uploadedimage'),
        ('newapp', '0010_defaultbannerimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='apppage',
            name='image',
            field=models.ForeignKey(blank=True, help_text='Banner image for page', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
    ]
