# Generated by Django 3.0.8 on 2020-07-30 08:34

from django.db import migrations, models
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0012_contactpage_formfield'),
    ]

    operations = [
        migrations.AddField(
            model_name='appcategory',
            name='intro',
            field=wagtail.core.fields.RichTextField(blank=True, help_text='Text to describe the category'),
        ),
        migrations.AlterField(
            model_name='apppage',
            name='date_published',
            field=models.DateField(verbose_name='Date article published'),
        ),
    ]
